### ISSUE TITLE
Images get cut off

### ISSUE THREAD

**Issue by ben4d85** [dockleryxk/ng-simple-slideshow#27]
**I am struggling to get this to work responsively on different device sizes!**

I simply cannot get this to work on different device sizes without getting my images *cut off*. All I want it to do is to display the image in 100% width, and calculate the height automatically.

Edit: I finally found a solution using `[backgroundSize]="'contain'"`, but it would be great if this could be added to the readme page. Especially the fact that is has to be `'contain'`, not just `contain`, i.e. with the extra `'`

**Comment by dockleryxk** [comment]
Some info: because you are using Angular bindings, and the backgroundSize property is a string, you must use a string.

When using the brackets ("[]") you are telling Angular that this property is essentially a javascript variable. If you were to take off the brackets, you would not need the quotation marks, because now Angular will assume this property value is a string.

**Comment by SubashKrishnan** [comment]
How can I implement, Image width should be 100% and height should be 300px...
If use backgroundSize : 'contain' the image is not cutoff...but width is cutoff...
